// Auto-generated — POS-typed pools for euphonic recovery keys.
// Key format: ADJ-NOUN-VERB-NOUN.
// Entropy: 9 + 10 + 9 + 10 = 38 bits.
window.YOLO_ADJ = [
  'abstract', 'achy', 'acidic', 'acoustic', 'adaptive', 'adrift', 'aglow', 'alien', 'aloof',
  'alpine', 'amber', 'ambient', 'analog', 'ancient', 'angular', 'ardent', 'arid', 'ashen',
  'atomic', 'auburn', 'austere', 'autumn', 'axial', 'barefoot', 'barren', 'bashful', 'battered',
  'beatific', 'bemoan', 'benign', 'bereft', 'binary', 'biotic', 'bitter', 'blank', 'bleak',
  'blessed', 'blithe', 'blurred', 'bold', 'bonny', 'bookish', 'boreal', 'bored', 'bounded',
  'braver', 'brazen', 'breezy', 'briny', 'broken', 'broody', 'brusque', 'buoyant', 'burdened',
  'buttery', 'calm', 'candid', 'cardinal', 'careless', 'carven', 'chary', 'cheerful', 'chill',
  'chilly', 'chipped', 'chiral', 'chosen', 'chrome', 'chronic', 'churlish', 'clammy', 'cleaner',
  'clinging', 'cloaked', 'cloudy', 'clueless', 'coarser', 'cobalt', 'coherent', 'cold', 'colour',
  'coltish', 'comely', 'coming', 'complex', 'concave', 'concrete', 'conical', 'constant', 'convex',
  'cornered', 'cosmic', 'cosy', 'courtly', 'coven', 'coy', 'cragged', 'cramped', 'crazy', 'creaky',
  'creased', 'crimson', 'cringing', 'crisp', 'crooked', 'cross', 'crumbled', 'crusted', 'cryptic',
  'crystal', 'cubic', 'culpable', 'cunning', 'curious', 'cursed', 'cursive', 'curt', 'cyclical',
  'cynic', 'daft', 'dainty', 'damp', 'dank', 'dappled', 'daring', 'daunted', 'dazed', 'dazzled',
  'dear', 'deepest', 'defiant', 'delicate', 'demure', 'desert', 'desolate', 'despair', 'devout',
  'dewy', 'dialect', 'diffuse', 'digital', 'dilated', 'dilute', 'dim', 'dimmed', 'dimpled',
  'dingy', 'dire', 'discrete', 'dismal', 'distal', 'distant', 'disused', 'divided', 'docile',
  'doleful', 'dorsal', 'dotted', 'doubtful', 'dowdy', 'drab', 'dread', 'dreamy', 'dried',
  'drifting', 'droll', 'drowsy', 'drunken', 'ducky', 'dull', 'dusky', 'dusted', 'dusty', 'dwarfed',
  'eager', 'earnest', 'earthy', 'ebbing', 'ebony', 'eclipsed', 'eerie', 'elastic', 'elated',
  'elder', 'electric', 'elegant', 'elegiac', 'elfin', 'elliptic', 'embered', 'emergent', 'eminent',
  'emptied', 'endless', 'enfolded', 'engulfed', 'enough', 'entropic', 'entropy', 'enzymic',
  'equable', 'errant', 'ethereal', 'euclid', 'euclidic', 'even', 'evened', 'everlit', 'evil',
  'exiled', 'exotic', 'expired', 'exponent', 'factual', 'faded', 'failing', 'faint', 'faithful',
  'fallen', 'fallible', 'falling', 'fallow', 'famished', 'famous', 'fancy', 'faraway', 'fast',
  'fated', 'fatigued', 'fawn', 'fearful', 'fecund', 'feeble', 'feral', 'ferine', 'ferric',
  'fervent', 'fickle', 'fierce', 'fiery', 'figured', 'final', 'fine', 'finer', 'finite', 'flawed',
  'fleeced', 'fleetest', 'fleshed', 'flighty', 'flimsy', 'flirty', 'flitted', 'flocked', 'flossy',
  'flown', 'fluent', 'fluffy', 'fluid', 'fond', 'foolish', 'forged', 'forgot', 'forked', 'forlorn',
  'formal', 'forsaken', 'fossil', 'foul', 'fractal', 'fragile', 'frail', 'frank', 'frantic',
  'frayed', 'frazzled', 'freak', 'freckled', 'frenzied', 'frosted', 'frothy', 'frowned', 'frowsy',
  'frugal', 'frumpy', 'full', 'funeral', 'furtive', 'fuzzy', 'galactic', 'gaseous', 'gaudy',
  'gauge', 'gauzy', 'genial', 'genteel', 'gentle', 'geodesic', 'ghastly', 'ghostly', 'gifted',
  'gilt', 'glacial', 'glacier', 'glad', 'glassy', 'glazed', 'gleaming', 'gleesome', 'glib',
  'glimmer', 'glinting', 'gloomy', 'glowing', 'glum', 'gnarled', 'godless', 'golden', 'gone',
  'good', 'goodly', 'gossamer', 'graced', 'graceful', 'gradient', 'grand', 'granite', 'granular',
  'grasping', 'grassy', 'grateful', 'grave', 'gravest', 'gravid', 'greenly', 'greyed', 'greyish',
  'grieving', 'grim', 'grimy', 'gusty', 'hale', 'halting', 'hapless', 'happy', 'hardy', 'harsh',
  'haughty', 'haunt', 'haunted', 'hawk', 'hazy', 'heady', 'hearty', 'heavy', 'hectic', 'heedful',
  'heirloom', 'helical', 'hermit', 'heroic', 'hexagon', 'hoarse', 'hollow', 'homely', 'homesick',
  'honest', 'honeyed', 'hooded', 'hopeful', 'horrid', 'hot', 'humble', 'humbled', 'humid',
  'hungry', 'hushed', 'hydric', 'icebound', 'icon', 'idle', 'immense', 'imminent', 'impish',
  'impure', 'inborn', 'inertial', 'infinite', 'infirm', 'inland', 'inmost', 'inner', 'innocent',
  'integral', 'intent', 'inward', 'ionic', 'ironic', 'isobaric', 'isotopic', 'jaded', 'jagged',
  'jaunty', 'jealous', 'jeering', 'jellied', 'jittered', 'jolly', 'jovial', 'joyless', 'joyous',
  'kinetic', 'laminar', 'languid', 'latent', 'laughing', 'lawless', 'lazy', 'leaden', 'leafy',
  'lean', 'lengthy', 'lenient', 'lethal', 'lexical', 'lightly', 'lilted', 'limbic', 'linear',
  'lissom', 'listless', 'lithe', 'lithic', 'little', 'lively', 'loamy', 'lofty', 'logical', 'lone',
  'lonely', 'long', 'lorn', 'lost', 'lovely', 'loving', 'lowest', 'lowfield', 'loyal', 'lucent',
  'lucid', 'lucky', 'lumpen', 'lunar', 'lurid', 'lustrous', 'magnetic', 'maple', 'marooned',
  'marred', 'marshy', 'massive', 'matted', 'mauve', 'median', 'meek', 'mellow', 'melodic',
  'menial', 'mere', 'merry', 'mesonic', 'messy', 'metric', 'microbe', 'midnight', 'midway', 'mild',
  'mindful', 'minor', 'mislaid', 'misted', 'misty', 'modular', 'moist', 'molar', 'molten', 'moody',
  'moon', 'moonlit', 'mopey', 'morose', 'mortal', 'mossy', 'mournful', 'mousy', 'moving',
  'muddied', 'muffled', 'muggy', 'muon', 'murky', 'mused', 'muted', 'myriad', 'mystic', 'mythic',
  'naive', 'narrow', 'nascent', 'natal', 'near', 'nebular',
];
if (YOLO_ADJ.length !== 512) throw new Error('YOLO_ADJ must be exactly 512 entries');
window.YOLO_NOUN = [
  'abbey', 'abyss', 'acorn', 'agate', 'airplane', 'algebra', 'alkali', 'alphabet', 'altar',
  'amber', 'amethyst', 'amp', 'ampere', 'amulet', 'analog', 'anchor', 'angle', 'angstrom', 'anion',
  'ankle', 'anode', 'antimass', 'antinode', 'antler', 'anvil', 'apex', 'apogee', 'apple',
  'apricot', 'apron', 'apsis', 'aqueduct', 'aquifer', 'arbor', 'arc', 'archer', 'archway', 'argon',
  'arrow', 'artifice', 'ash', 'ashfall', 'ashram', 'aspect', 'aspens', 'aster', 'asteroid',
  'atelier', 'atom', 'attic', 'auger', 'aura', 'autopsy', 'autumn', 'awl', 'axiom', 'axis',
  'azalea', 'azimuth', 'azure', 'badge', 'bailey', 'baker', 'balcony', 'bale', 'balefire',
  'ballad', 'band', 'bandage', 'bangle', 'banner', 'barge', 'bark', 'barley', 'barrel', 'basalt',
  'basilica', 'basin', 'bastion', 'bath', 'batik', 'bay', 'bayberry', 'bazaar', 'beacon', 'beagle',
  'beaker', 'beam', 'bear', 'bedding', 'bedlam', 'beech', 'beehive', 'beetle', 'beggar', 'belfry',
  'bellow', 'belly', 'bergamot', 'berry', 'beryl', 'bezoar', 'bier', 'binary', 'bindweed', 'biome',
  'biont', 'biopsy', 'birch', 'bird', 'bismuth', 'bison', 'bivouac', 'blade', 'blanket', 'blazon',
  'blessing', 'blizzard', 'block', 'blood', 'bloom', 'blossom', 'blotch', 'bluebell', 'bluebird',
  'bluejay', 'blush', 'bluster', 'bobcat', 'bog', 'bolt', 'bonfire', 'book', 'bookmark', 'boolean',
  'border', 'boreal', 'borealis', 'boson', 'bough', 'boulder', 'bouquet', 'bowery', 'bowsprit',
  'boxwood', 'bramble', 'branch', 'brane', 'brass', 'bread', 'breeze', 'brew', 'briar', 'brick',
  'bridge', 'brigand', 'brine', 'brink', 'brisket', 'brocade', 'broker', 'brook', 'broom', 'broth',
  'brow', 'bubble', 'buckle', 'buckler', 'bud', 'bulwark', 'bundle', 'bungalow', 'burden', 'burn',
  'burrow', 'bushel', 'butter', 'cabin', 'cabinet', 'cadmium', 'cairn', 'cake', 'calcite',
  'calendar', 'calfskin', 'calibre', 'calico', 'caliper', 'calliope', 'calm', 'calorie', 'camel',
  'camp', 'campfire', 'camphor', 'canal', 'candle', 'cane', 'canopy', 'canyon', 'cap', 'caper',
  'capstone', 'capsule', 'caravan', 'carbon', 'carboy', 'cardoon', 'carrot', 'cart', 'case',
  'castle', 'cat', 'cation', 'catkin', 'caulk', 'cavalry', 'cave', 'caveat', 'cavern', 'cavity',
  'cedar', 'celadon', 'cellar', 'cellist', 'cepheid', 'cepheus', 'chalice', 'chamber', 'chamois',
  'champion', 'chandler', 'chantry', 'chap', 'chapbook', 'char', 'charcoal', 'charm', 'chart',
  'chasm', 'chasuble', 'cheek', 'cherry', 'chess', 'chestnut', 'chimera', 'chimney', 'chintz',
  'chip', 'chirrup', 'chisel', 'chlorite', 'chord', 'chortle', 'chroma', 'chronos', 'churn',
  'cicada', 'cider', 'cinder', 'circle', 'circuit', 'cistern', 'citadel', 'citrine', 'cladon',
  'claret', 'clarinet', 'clasp', 'clay', 'claymore', 'clef', 'cleric', 'cliff', 'clinker', 'cloak',
  'clock', 'cloister', 'cloth', 'clove', 'clover', 'cluster', 'coal', 'cobalt', 'cocoa', 'coffin',
  'coil', 'coin', 'coinage', 'coincide', 'colossus', 'column', 'comb', 'comet', 'comfort',
  'compass', 'compline', 'computer', 'concave', 'cone', 'conifer', 'constant', 'contour', 'convex',
  'copper', 'coral', 'core', 'corner', 'corona', 'coronet', 'corridor', 'corsage', 'cortege',
  'cortex', 'cosecant', 'cosine', 'cosmos', 'cot', 'cottage', 'cougar', 'coulomb', 'counsel',
  'cove', 'covenant', 'coverlet', 'cradle', 'crag', 'cranny', 'crater', 'creel', 'creep', 'crest',
  'cricket', 'crier', 'crocus', 'crosier', 'crow', 'crown', 'crucible', 'crumb', 'crust', 'cuckoo',
  'cup', 'cupola', 'curfew', 'curl', 'current', 'curtain', 'curve', 'cushion', 'cycle', 'cyclone',
  'cypress', 'daffodil', 'dagger', 'daisy', 'darnel', 'dawn', 'decibel', 'degree', 'delta', 'den',
  'density', 'derive', 'devotion', 'dew', 'dewdrop', 'dial', 'diamond', 'diocese', 'diode',
  'dipole', 'dirge', 'dock', 'doe', 'dolmen', 'domain', 'donkey', 'door', 'dovecote', 'down',
  'draft', 'drape', 'drapery', 'drawer', 'dream', 'drizzle', 'druid', 'drum', 'dryad', 'dulcimer',
  'dumpling', 'dusk', 'dyad', 'dynamo', 'eaglet', 'eaves', 'ebony', 'echo', 'eclipse', 'eddy',
  'edge', 'eelgrass', 'eigen', 'electron', 'element', 'elf', 'elixir', 'elk', 'elkhorn', 'ellipse',
  'ember', 'embers', 'energy', 'entropy', 'enzyme', 'epilogue', 'epistle', 'epoch', 'equation',
  'equerry', 'erg', 'ergodic', 'escape', 'essay', 'ether', 'evening', 'ewer', 'fable', 'falconry',
  'fallow', 'fauna', 'feastday', 'feather', 'fell', 'fen', 'fennec', 'fennel', 'fermion', 'fern',
  'fernwood', 'ferry', 'festival', 'fiddle', 'field', 'figurine', 'filbert', 'fillet', 'filly',
  'filter', 'finality', 'finial', 'fir', 'fireside', 'fjord', 'flag', 'flake', 'flame', 'flamingo',
  'flax', 'flight', 'flint', 'flood', 'floor', 'flora', 'florist', 'fluff', 'fluorine', 'flux',
  'foal', 'foam', 'focus', 'fog', 'follicle', 'foolscap', 'foothill', 'foothold', 'forage',
  'forbear', 'forest', 'forge', 'forth', 'fortune', 'fossil', 'fount', 'fountain', 'fox',
  'fractal', 'fraction', 'fragment', 'freckle', 'friary', 'fringe', 'frock', 'frost', 'fruit',
  'function', 'furnace', 'furrow', 'fusion', 'gadget', 'galaxy', 'gale', 'gallon', 'gambit',
  'gamma', 'garden', 'gardener', 'garland', 'garret', 'gauge', 'gauntlet', 'gazebo', 'geese',
  'geisha', 'gene', 'gentian', 'geode', 'geoid', 'geometry', 'ghost', 'gingham', 'giraffe',
  'girder', 'glade', 'glass', 'glaze', 'gleam', 'glee', 'glimpse', 'globe', 'glow', 'glowworm',
  'glucose', 'gluon', 'gnome', 'gnomon', 'gold', 'goose', 'gourd', 'grackle', 'gradient', 'grain',
  'gram', 'granary', 'granite', 'granule', 'graph', 'graphene', 'grass', 'gravel', 'graviton',
  'grebe', 'greenery', 'grotto', 'grove', 'gryphon', 'gull', 'gullwing', 'gully', 'gust', 'gutter',
  'hadron', 'hail', 'halcyon', 'halibut', 'halide', 'halite', 'hallway', 'halo', 'hamlet',
  'hammer', 'hammock', 'harbour', 'hare', 'harp', 'harvest', 'hassock', 'hatch', 'haven',
  'hawthorn', 'haystack', 'hazel', 'headland', 'hearth', 'heather', 'hedge', 'helios', 'helium',
  'helix', 'helmet', 'hem', 'hemlock', 'henbane', 'herald', 'herdsman', 'heroine', 'heron',
  'hertz', 'hickory', 'highland', 'highroad', 'hilbert', 'hill', 'hillside', 'hinge', 'hollow',
  'hologram', 'honey', 'honeydew', 'hook', 'horizon', 'hornbook', 'hornpipe', 'horse', 'house',
  'hush', 'hyacinth', 'hydride', 'hydrogen', 'ibex', 'ice', 'icehouse', 'icicle', 'idyll',
  'infinity', 'infrared', 'inkwell', 'insignia', 'integer', 'integral', 'ion', 'iris', 'iron',
  'ironwood', 'island', 'isotope', 'ivory', 'ivy', 'jackdaw', 'jacobian', 'jade', 'jamboree',
  'jar', 'jay', 'jeweller', 'jongleur', 'joule', 'journal', 'joust', 'jubilee', 'juncture',
  'juniper', 'kapok', 'keepsafe', 'keepsake', 'kelp', 'kelvin', 'kepler', 'kernel', 'kestrel',
  'kettle', 'keystone', 'kiln', 'kimono', 'king', 'kitchen', 'kite', 'kitten', 'knapsack', 'knoll',
  'knot', 'knothole', 'kohlrabi', 'koinonia', 'label', 'lace', 'ladder', 'lagoon', 'lair', 'lake',
  'lakebed', 'lamb', 'lambda', 'lancer', 'landfall', 'lanolin', 'lantern', 'larkspur', 'latch',
  'lattice', 'lavender', 'laynet', 'leaf', 'ledge', 'legend', 'lemma', 'lemon', 'lens', 'lichen',
  'lifeline', 'ligand', 'ligature', 'lilac', 'lilting', 'limit', 'linen', 'linnet', 'lint', 'lion',
  'liquid', 'liver', 'loaf', 'locket', 'locus', 'loft', 'logbook', 'logic', 'logos', 'loquat',
  'lore', 'lotus', 'loveseat', 'lullaby', 'lumen', 'luminary', 'lunar', 'lunaria', 'lynx', 'lyre',
  'lyrebird', 'magneto', 'magnolia', 'magpie', 'mahogany', 'mallow', 'mammal', 'mango', 'mantissa',
  'mantle', 'maple', 'mapping', 'marble', 'marigold', 'marimba', 'mariner', 'marker', 'mask',
  'mass', 'matinee', 'matrix', 'matron', 'matter', 'mattress', 'meadow', 'mean', 'median',
  'memento', 'memoir', 'meniscus', 'menthol', 'merchant', 'meridian', 'meringue', 'merlin', 'mesa',
  'meson', 'metal', 'meteor', 'micron', 'midden', 'midnight', 'mildew', 'mill', 'minaret',
  'mindful', 'mineral', 'mink', 'minnow', 'mint', 'mire', 'mirror', 'miso', 'mist', 'mocha',
  'mochi', 'modulus', 'molar', 'mole', 'molecule', 'moment', 'momentum', 'monad', 'monk', 'moon',
  'moonbow', 'moor', 'moss', 'moth', 'motor', 'mouse', 'muffin', 'muon', 'mushroom', 'muslin',
  'nap', 'napkin', 'nebula', 'nebular', 'nectar', 'needle', 'neon', 'nephron', 'nest', 'nettle',
  'network', 'neuron', 'neutrino', 'neutron', 'newcomer', 'newt', 'newton', 'nexus', 'niche',
  'nicotine', 'nimbus', 'node', 'nook', 'noon', 'norm', 'nose', 'notch', 'nova', 'novel',
  'novella', 'nucleus', 'nuclide', 'nugget', 'numeral', 'oak', 'oats', 'obelisk', 'obelus',
  'ocean', 'octagon', 'octant', 'ogre', 'ohm', 'oleander', 'olive', 'omega', 'onion', 'operator',
  'operetta', 'optic', 'optics', 'oracle', 'orange', 'orangery', 'orbit', 'orbital', 'orchid',
  'ordinate', 'oriel', 'orient', 'origin', 'orlop', 'otter', 'outlier', 'overcoat', 'overlook',
  'owl', 'oxygen', 'paddle', 'pagoda', 'palace', 'palette', 'palisade', 'palm', 'palomino',
  'panel', 'pangolin', 'panorama', 'pantry', 'parable', 'parabola', 'paramour', 'parity', 'parlor',
  'parlour', 'parquet', 'parsec', 'parsley', 'particle', 'parton', 'pascal', 'passport', 'pastel',
  'pasture', 'paw', 'peacoat', 'peafowl', 'pear', 'pearl', 'peat', 'pebble', 'peerless', 'pelican',
  'pelt', 'pendant', 'pendulum', 'pentad', 'peony', 'pepper', 'pergola', 'peridot', 'perigee',
  'petal', 'pewter', 'phase', 'phosphor', 'photon', 'pigeon', 'pilchard', 'pilgrim', 'pillar',
  'pillow', 'pine', 'pinecone', 'pinelike', 'placard', 'plain', 'plane', 'plasma', 'plateau',
  'platinum', 'plumage', 'plume', 'plumeria', 'pocket', 'polestar', 'pollen', 'polygon', 'polymer',
  'polytope', 'pomelo', 'poncho', 'pond', 'pondweed', 'pool', 'poppy', 'porch', 'portage',
  'portal', 'porthole', 'portico', 'positron', 'postbox', 'potter', 'prairie', 'praxis', 'precept',
  'precinct', 'primrose', 'prism', 'promise', 'proton', 'prowler', 'puddle', 'puffin', 'pulsar',
  'pulse', 'pumpkin', 'purl', 'quadrant', 'quagmire', 'quail', 'quanta', 'quantum', 'quark',
  'quarter', 'quartz', 'queendom', 'quench', 'quibble', 'quill', 'quilt', 'quilting', 'quince',
  'quiver', 'quotient', 'rabbit', 'radian', 'radical', 'radish', 'radius', 'raft', 'rail',
  'railcar', 'rainbow', 'ramble', 'ramshorn', 'ratio', 'raven', 'ravine', 'ray', 'reaction',
  'reactor', 'realm', 'recluse', 'redwood', 'reed', 'reef', 'reflex', 'refuge', 'region', 'relic',
  'remnant', 'requiem', 'resistor', 'reverie', 'rhea', 'rhombus', 'ribbon',
];
if (YOLO_NOUN.length !== 1024) throw new Error('YOLO_NOUN must be exactly 1024 entries');
window.YOLO_VERB = [
  'absorbs', 'accretes', 'aches', 'adores', 'adorns', 'advances', 'agitates', 'ails', 'alights',
  'aligns', 'alters', 'amazes', 'analyses', 'anchors', 'answers', 'apes', 'appears', 'arches',
  'arcs', 'arises', 'ascends', 'asks', 'assures', 'attends', 'attracts', 'averages', 'avoids',
  'awaits', 'awakens', 'awes', 'balances', 'balms', 'banishes', 'banks', 'banters', 'bares',
  'barters', 'basks', 'battles', 'bays', 'beams', 'beckons', 'becomes', 'begets', 'beguiles',
  'believes', 'belongs', 'bends', 'berates', 'biases', 'bides', 'binds', 'bisects', 'bites',
  'blazes', 'blears', 'bleeds', 'blends', 'blesses', 'blinks', 'blooms', 'blossoms', 'blows',
  'boils', 'bonds', 'branches', 'bridges', 'broods', 'brushes', 'buffers', 'builds', 'bundles',
  'burns', 'bustles', 'buzzes', 'calcines', 'calls', 'calms', 'cancels', 'canoes', 'cares',
  'carols', 'carves', 'casts', 'catches', 'catnaps', 'caves', 'ceases', 'centers', 'chains',
  'chants', 'charges', 'charms', 'chases', 'chats', 'cheers', 'chills', 'chimes', 'chirps',
  'chokes', 'chooses', 'circles', 'clamors', 'clangs', 'clasps', 'claws', 'cleans', 'clears',
  'climbs', 'clings', 'closes', 'clouds', 'clusters', 'clutches', 'coaxes', 'coheres', 'collects',
  'combines', 'combs', 'comes', 'comforts', 'commands', 'composes', 'computes', 'conducts',
  'conjures', 'connects', 'consoles', 'contains', 'contends', 'cooks', 'cools', 'coos', 'corrodes',
  'cowers', 'crackles', 'crafts', 'craves', 'crawls', 'creaks', 'creates', 'creeps', 'crests',
  'cringes', 'crosses', 'crouches', 'crowns', 'cruises', 'cubs', 'curls', 'curves', 'cycles',
  'dabbles', 'dances', 'darns', 'dashes', 'dawdles', 'dawns', 'dazzles', 'deafens', 'decays',
  'deceives', 'declares', 'deduces', 'deepens', 'defies', 'defines', 'deflates', 'deflects',
  'deforms', 'delays', 'delivers', 'demands', 'denotes', 'departs', 'depicts', 'derives',
  'desalts', 'descends', 'despairs', 'detects', 'detours', 'devours', 'diffuses', 'dilates',
  'dims', 'dines', 'dips', 'dissents', 'distills', 'diverges', 'dives', 'divides', 'divines',
  'dotes', 'doubles', 'doubts', 'dozes', 'drapes', 'draws', 'dreams', 'drifts', 'drinks', 'drips',
  'droops', 'drops', 'drowses', 'drums', 'dwells', 'earns', 'eases', 'ebbs', 'echoes', 'eclipses',
  'eddies', 'edges', 'elects', 'elevates', 'embers', 'embodies', 'embraces', 'emerges', 'emits',
  'empties', 'enacts', 'encloses', 'encodes', 'ends', 'endures', 'enfolds', 'enforces', 'engulfs',
  'enjoys', 'enlivens', 'ensnares', 'enters', 'entwines', 'envies', 'enwraps', 'erases', 'escapes',
  'espies', 'evens', 'evolves', 'excites', 'exhales', 'exists', 'expands', 'exposes', 'extends',
  'extrudes', 'factors', 'fades', 'fails', 'falters', 'fancies', 'fans', 'farrows', 'fasts',
  'fathoms', 'favors', 'fears', 'fends', 'ferries', 'fetches', 'fettles', 'fidgets', 'filters',
  'finds', 'fires', 'fishes', 'fits', 'fixes', 'flashes', 'flees', 'flickers', 'flinches',
  'flings', 'floats', 'floods', 'flows', 'flurries', 'flushes', 'flutters', 'focuses', 'folds',
  'follows', 'foments', 'forages', 'forbids', 'forgets', 'forgives', 'forms', 'frames', 'frees',
  'freezes', 'frets', 'frolics', 'frosts', 'frowns', 'fulfills', 'furls', 'fuses', 'gambles',
  'gathers', 'gazes', 'gentles', 'glances', 'gleams', 'glides', 'glimmers', 'glints', 'glistens',
  'glitters', 'gloats', 'glooms', 'glows', 'gnashes', 'goes', 'grabs', 'graces', 'grasps',
  'grazes', 'greets', 'grieves', 'grimaces', 'grinds', 'grins', 'grips', 'groans', 'grooms',
  'grounds', 'grouses', 'growls', 'guards', 'guesses', 'guests', 'guides', 'gushes', 'hallows',
  'halts', 'halves', 'handles', 'hangs', 'happens', 'harkens', 'harrows', 'harvests', 'hastens',
  'hatches', 'hates', 'hauls', 'haunts', 'heals', 'hears', 'heartens', 'heats', 'heaves', 'hedges',
  'heeds', 'heels', 'hems', 'herds', 'hides', 'hinges', 'hints', 'hisses', 'hoards', 'holds',
  'hollers', 'hollows', 'homes', 'honeys', 'hopes', 'hovers', 'howls', 'huddles', 'hulls',
  'hungers', 'hunts', 'hurries', 'hurts', 'hushes', 'hustles', 'hymns', 'idles', 'ignites',
  'illumes', 'imagines', 'imbibes', 'implies', 'implodes', 'imports', 'indexes', 'indicts',
  'induces', 'indulges', 'infers', 'inflames', 'inflects', 'ingests', 'inhales', 'inherits',
  'injects', 'insists', 'insures', 'intones', 'invades', 'invents', 'inverts', 'invites',
  'ionizes', 'isolates', 'iterates', 'joins', 'jokes', 'journeys', 'joys', 'judges', 'juggles',
  'jumps', 'keeps', 'kindles', 'kisses', 'kneads', 'kneels', 'knots', 'knows', 'labors', 'lacks',
  'ladles', 'lags', 'lambs', 'laments', 'lances', 'lapses', 'lasers', 'lashes', 'lasts', 'latches',
  'laughs', 'launches', 'laves', 'lavishes', 'leads', 'leans', 'leaps', 'learns', 'leaves',
  'lectures', 'leers', 'lends', 'lenses', 'lessens', 'letters', 'levels', 'licks', 'lightens',
  'lights', 'likens', 'lilts', 'limits', 'lingers', 'links', 'listens', 'litters', 'lives',
  'loathes', 'locks', 'lodges', 'logs', 'loiters', 'lolls', 'looks', 'looms', 'loops', 'lopes',
  'lords', 'loses', 'lounges', 'loves', 'lowers', 'lubes', 'lulls', 'lumbers', 'lunges', 'lures',
  'lurks', 'maps', 'matches', 'measures', 'melts', 'mends', 'merges', 'migrates', 'mirrors',
  'models', 'monitors', 'morphs', 'motions', 'mourns', 'muses', 'mutates', 'nears', 'nests',
  'nods', 'notates', 'nudges', 'obeys', 'oblongs', 'observes', 'obtains',
];
if (YOLO_VERB.length !== 512) throw new Error('YOLO_VERB must be exactly 512 entries');
// Legacy export kept so any cached consumer doesn't break.
window.YOLO_WORDLIST = YOLO_NOUN;
