// Auto-generated — POS-typed pools for euphonic recovery keys.
// Key format: ADJ-NOUN-VERB-NOUN.
// Entropy: 9 + 10 + 9 + 10 = 38 bits.
window.YOLO_ADJ = [
  'achy', 'adrift', 'aglow', 'alien', 'aloof', 'amber', 'ancient', 'ardent', 'arid', 'ashen',
  'auburn', 'austere', 'autumn', 'barefoot', 'barren', 'bashful', 'battered', 'beatific', 'bemoan',
  'bereft', 'bitter', 'blank', 'bleak', 'blessed', 'blithe', 'blurred', 'bold', 'bonny', 'bookish',
  'bored', 'braver', 'brazen', 'breezy', 'briny', 'broken', 'broody', 'brusque', 'buoyant',
  'burdened', 'buttery', 'calm', 'candid', 'careless', 'carven', 'chary', 'cheerful', 'chill',
  'chilly', 'chipped', 'chosen', 'chrome', 'churlish', 'clammy', 'cleaner', 'clinging', 'cloaked',
  'cloudy', 'clueless', 'coarser', 'cold', 'colour', 'coltish', 'comely', 'coming', 'cornered',
  'cosy', 'courtly', 'coven', 'coy', 'cragged', 'cramped', 'crazy', 'creaky', 'creased', 'crimson',
  'cringing', 'crisp', 'crooked', 'cross', 'crumbled', 'crusted', 'cryptic', 'culpable', 'cunning',
  'curious', 'cursed', 'cursive', 'curt', 'cynic', 'daft', 'dainty', 'damp', 'dank', 'dappled',
  'daring', 'daunted', 'dazed', 'dazzled', 'dear', 'deepest', 'defiant', 'delicate', 'demure',
  'desert', 'desolate', 'despair', 'devout', 'dewy', 'dialect', 'diffuse', 'dim', 'dimmed',
  'dimpled', 'dingy', 'dire', 'dismal', 'disused', 'divided', 'docile', 'doleful', 'dotted',
  'doubtful', 'dowdy', 'drab', 'dread', 'dreamy', 'dried', 'drifting', 'droll', 'drowsy',
  'drunken', 'ducky', 'dull', 'dusky', 'dusted', 'dusty', 'dwarfed', 'eager', 'earnest', 'earthy',
  'ebbing', 'ebony', 'eerie', 'elated', 'elder', 'elegant', 'elegiac', 'elfin', 'embered',
  'eminent', 'emptied', 'endless', 'enfolded', 'engulfed', 'enough', 'errant', 'ethereal',
  'evened', 'everlit', 'evil', 'exiled', 'exotic', 'expired', 'faded', 'failing', 'faint',
  'faithful', 'fallen', 'fallible', 'fallow', 'famished', 'famous', 'fancy', 'faraway', 'fast',
  'fated', 'fatigued', 'fawn', 'fearful', 'fecund', 'feeble', 'ferine', 'fervent', 'fickle',
  'fierce', 'fiery', 'figured', 'final', 'fine', 'finer', 'finite', 'flawed', 'fleeced',
  'fleetest', 'fleshed', 'flighty', 'flimsy', 'flirty', 'flitted', 'flocked', 'flossy', 'flown',
  'fluent', 'fluffy', 'fluid', 'fond', 'foolish', 'forged', 'forgot', 'forlorn', 'forsaken',
  'fossil', 'foul', 'fragile', 'frail', 'frank', 'frantic', 'frayed', 'frazzled', 'freak',
  'freckled', 'frenzied', 'frosted', 'frothy', 'frowned', 'frowsy', 'frugal', 'frumpy', 'full',
  'funeral', 'furtive', 'fuzzy', 'gaudy', 'gauzy', 'genial', 'genteel', 'gentle', 'ghastly',
  'ghostly', 'gifted', 'gilt', 'glacier', 'glad', 'glassy', 'glazed', 'gleaming', 'gleesome',
  'glib', 'glimmer', 'glinting', 'gloomy', 'glum', 'gnarled', 'godless', 'golden', 'gone', 'good',
  'goodly', 'gossamer', 'graced', 'graceful', 'grand', 'granite', 'grasping', 'grassy', 'grateful',
  'grave', 'gravest', 'greenly', 'greyed', 'greyish', 'grieving', 'grim', 'grimy', 'gusty', 'hale',
  'halting', 'hapless', 'happy', 'hardy', 'harsh', 'haughty', 'haunt', 'haunted', 'hawk', 'hazy',
  'heady', 'hearty', 'heavy', 'hectic', 'heedful', 'heirloom', 'hermit', 'heroic', 'hoarse',
  'hollow', 'homely', 'homesick', 'honest', 'honeyed', 'hooded', 'hopeful', 'horrid', 'hot',
  'humble', 'humbled', 'humid', 'hungry', 'hushed', 'icebound', 'icon', 'idle', 'immense',
  'imminent', 'impish', 'impure', 'inborn', 'infirm', 'inland', 'inmost', 'inner', 'innocent',
  'intent', 'inward', 'ironic', 'jaded', 'jagged', 'jaunty', 'jealous', 'jeering', 'jellied',
  'jittered', 'jolly', 'jovial', 'joyless', 'joyous', 'languid', 'latent', 'laughing', 'lawless',
  'lazy', 'leaden', 'leafy', 'lean', 'lengthy', 'lenient', 'lethal', 'lightly', 'lilted', 'lissom',
  'listless', 'lithe', 'little', 'lively', 'loamy', 'lofty', 'lone', 'lonely', 'long', 'lorn',
  'lost', 'lovely', 'loving', 'lowest', 'loyal', 'lucid', 'lucky', 'lumpen', 'lunar', 'lurid',
  'lustrous', 'maple', 'marooned', 'marred', 'marshy', 'matted', 'mauve', 'meek', 'mellow',
  'melodic', 'menial', 'mere', 'merry', 'messy', 'midnight', 'midway', 'mild', 'mindful', 'minor',
  'mislaid', 'misted', 'misty', 'moist', 'moody', 'moon', 'moonlit', 'mopey', 'morose', 'mortal',
  'mossy', 'mournful', 'mousy', 'moving', 'muddied', 'muffled', 'muggy', 'murky', 'mused', 'muted',
  'mystic', 'mythic', 'naive', 'narrow', 'nascent', 'near', 'neglect', 'nervous', 'nettle',
  'nimble', 'noble', 'noctic', 'noisy', 'nomadic', 'nothing', 'nowhere', 'obdurate', 'obscure',
  'obvious', 'odious', 'olden', 'omened', 'omitted', 'opaque', 'ordered', 'orphic', 'other',
  'outcast', 'overdue', 'overlit', 'overran', 'owlish', 'sacred', 'secret', 'seldom', 'selfless',
  'serene', 'severe', 'shaded', 'shady', 'shaken', 'shallow', 'shared', 'sharp', 'sheer',
  'shifting', 'shining', 'shiny', 'shrewd', 'shrill', 'shy', 'silent', 'silken', 'silvery',
  'simple', 'sincere', 'sinful', 'single', 'sinuous', 'skittish', 'slack', 'sleek', 'sleepy',
  'slender', 'slight', 'slim', 'slow', 'sluggish', 'small', 'smoky', 'smooth', 'sober', 'soft',
  'solemn', 'solid', 'solitary', 'somber', 'sombre', 'soothing', 'sooty', 'sound', 'sour',
  'sparse', 'spectral', 'spent', 'spiced', 'spiny', 'spotless', 'spotted', 'steamy', 'steely',
  'stellar', 'stern', 'stifling', 'still', 'stilled', 'stilted', 'stingy', 'stoic', 'stony',
  'stormy', 'straight', 'strange',
];
if (YOLO_ADJ.length !== 512) throw new Error('YOLO_ADJ must be exactly 512 entries');
window.YOLO_NOUN = [
  'abbey', 'abyss', 'acorn', 'agate', 'airplane', 'alphabet', 'altar', 'amber', 'amethyst',
  'amulet', 'anchor', 'angle', 'ankle', 'antler', 'anvil', 'apex', 'apple', 'apricot', 'apron',
  'aqueduct', 'aquifer', 'arbor', 'archer', 'archway', 'arrow', 'artifice', 'ash', 'ashfall',
  'ashram', 'aspect', 'aspens', 'aster', 'atelier', 'attic', 'aura', 'autopsy', 'autumn', 'awl',
  'axiom', 'azalea', 'azure', 'badge', 'bailey', 'baker', 'balcony', 'bale', 'balefire', 'ballad',
  'band', 'bandage', 'bangle', 'banner', 'barge', 'bark', 'barley', 'barrel', 'basalt', 'basilica',
  'bastion', 'bath', 'batik', 'bay', 'bayberry', 'bazaar', 'beacon', 'beagle', 'beaker', 'beam',
  'bear', 'bedding', 'bedlam', 'beech', 'beehive', 'beetle', 'beggar', 'belfry', 'bellow', 'belly',
  'bergamot', 'berry', 'bezoar', 'bier', 'bindweed', 'birch', 'bird', 'bison', 'bivouac', 'blade',
  'blanket', 'blazon', 'blessing', 'blizzard', 'block', 'blood', 'bloom', 'blossom', 'blotch',
  'bluebell', 'bluebird', 'bluejay', 'blush', 'bluster', 'bobcat', 'bog', 'bolt', 'bonfire',
  'book', 'bookmark', 'border', 'boreal', 'borealis', 'bough', 'boulder', 'bouquet', 'bowery',
  'bowsprit', 'boxwood', 'bramble', 'branch', 'brass', 'bread', 'breeze', 'brew', 'briar', 'brick',
  'bridge', 'brigand', 'brine', 'brink', 'brisket', 'brocade', 'broker', 'brook', 'broom', 'broth',
  'brow', 'bubble', 'buckle', 'buckler', 'bud', 'bulwark', 'bundle', 'bungalow', 'burden', 'burn',
  'burrow', 'bushel', 'butter', 'cabin', 'cabinet', 'cairn', 'cake', 'calendar', 'calfskin',
  'calico', 'caliper', 'calliope', 'calm', 'camel', 'camp', 'campfire', 'camphor', 'canal',
  'candle', 'cane', 'canyon', 'cap', 'caper', 'capstone', 'caravan', 'cardoon', 'carrot', 'cart',
  'case', 'castle', 'cat', 'catkin', 'caulk', 'cavalry', 'cave', 'cavern', 'cedar', 'celadon',
  'cellar', 'cellist', 'chalice', 'chamber', 'chamois', 'champion', 'chandler', 'chantry', 'chap',
  'chapbook', 'char', 'charcoal', 'charm', 'chart', 'chasm', 'chasuble', 'cheek', 'cherry',
  'chess', 'chestnut', 'chimera', 'chimney', 'chintz', 'chip', 'chirrup', 'chisel', 'chortle',
  'churn', 'cicada', 'cider', 'cinder', 'circle', 'cistern', 'citadel', 'citrine', 'claret',
  'clarinet', 'clasp', 'clay', 'claymore', 'clef', 'cleric', 'cliff', 'clinker', 'cloak', 'clock',
  'cloister', 'cloth', 'clove', 'clover', 'cluster', 'coal', 'cobalt', 'cocoa', 'coffin', 'coin',
  'coinage', 'colossus', 'column', 'comb', 'comet', 'comfort', 'compass', 'compline', 'cone',
  'conifer', 'copper', 'coral', 'corner', 'coronet', 'corridor', 'corsage', 'cortege', 'cot',
  'cottage', 'cougar', 'counsel', 'cove', 'covenant', 'coverlet', 'cradle', 'crag', 'cranny',
  'crater', 'creel', 'creep', 'crest', 'cricket', 'crier', 'crocus', 'crosier', 'crow', 'crown',
  'crucible', 'crumb', 'crust', 'cuckoo', 'cup', 'cupola', 'curfew', 'curl', 'curtain', 'cushion',
  'cypress', 'daffodil', 'dagger', 'daisy', 'darnel', 'dawn', 'delta', 'den', 'devotion', 'dew',
  'dewdrop', 'dial', 'diamond', 'diocese', 'dirge', 'dock', 'doe', 'dolmen', 'donkey', 'door',
  'dovecote', 'down', 'draft', 'drape', 'drapery', 'drawer', 'dream', 'drizzle', 'druid', 'drum',
  'dryad', 'dulcimer', 'dumpling', 'dusk', 'eaglet', 'eaves', 'ebony', 'echo', 'eelgrass', 'elf',
  'elk', 'elkhorn', 'ember', 'embers', 'epilogue', 'epistle', 'epoch', 'equerry', 'escape',
  'essay', 'ether', 'evening', 'ewer', 'fable', 'falconry', 'fallow', 'fauna', 'feastday',
  'feather', 'fell', 'fen', 'fennec', 'fennel', 'fern', 'fernwood', 'ferry', 'festival', 'fiddle',
  'field', 'figurine', 'filbert', 'fillet', 'filly', 'finality', 'finial', 'fir', 'fireside',
  'fjord', 'flag', 'flake', 'flame', 'flamingo', 'flax', 'flight', 'flint', 'flood', 'floor',
  'flora', 'florist', 'fluff', 'foal', 'foam', 'fog', 'follicle', 'foolscap', 'foothill',
  'foothold', 'forage', 'forbear', 'forest', 'forge', 'forth', 'fortune', 'fossil', 'fount',
  'fountain', 'fox', 'fragment', 'freckle', 'friary', 'fringe', 'frock', 'frost', 'fruit',
  'furnace', 'furrow', 'gadget', 'gale', 'gallon', 'gambit', 'garden', 'gardener', 'garland',
  'garret', 'gauntlet', 'gazebo', 'geese', 'geisha', 'gentian', 'ghost', 'gingham', 'giraffe',
  'girder', 'glade', 'glass', 'glaze', 'gleam', 'glee', 'glimpse', 'globe', 'glow', 'glowworm',
  'gnome', 'gnomon', 'gold', 'goose', 'gourd', 'grackle', 'grain', 'granary', 'granite', 'grass',
  'gravel', 'grebe', 'greenery', 'grotto', 'grove', 'gryphon', 'gull', 'gullwing', 'gully', 'gust',
  'gutter', 'hail', 'halcyon', 'halibut', 'hallway', 'halo', 'hamlet', 'hammer', 'hammock',
  'harbour', 'hare', 'harp', 'harvest', 'hassock', 'hatch', 'haven', 'hawthorn', 'haystack',
  'hazel', 'headland', 'hearth', 'heather', 'hedge', 'helios', 'helmet', 'hem', 'hemlock',
  'henbane', 'herald', 'herdsman', 'heroine', 'heron', 'hickory', 'highland', 'highroad', 'hill',
  'hillside', 'hollow', 'honey', 'honeydew', 'hook', 'horizon', 'hornbook', 'hornpipe', 'horse',
  'house', 'hush', 'hyacinth', 'ibex', 'ice', 'icehouse', 'icicle', 'idyll', 'inkwell', 'insignia',
  'iris', 'iron', 'ironwood', 'island', 'ivory', 'ivy', 'jackdaw', 'jade', 'jamboree', 'jar',
  'jay', 'jeweller', 'jongleur', 'journal', 'joust', 'jubilee', 'juncture', 'juniper', 'kapok',
  'keepsafe', 'keepsake', 'kelp', 'kestrel', 'kettle', 'keystone', 'kiln', 'kimono', 'king',
  'kitchen', 'kite', 'kitten', 'knapsack', 'knoll', 'knot', 'knothole', 'kohlrabi', 'koinonia',
  'label', 'lace', 'ladder', 'lagoon', 'lair', 'lake', 'lakebed', 'lamb', 'lancer', 'landfall',
  'lanolin', 'lantern', 'larkspur', 'latch', 'lattice', 'lavender', 'laynet', 'leaf', 'ledge',
  'legend', 'lemon', 'lichen', 'lifeline', 'lilac', 'lilting', 'linen', 'linnet', 'lint', 'lion',
  'liver', 'loaf', 'locket', 'loft', 'logbook', 'loquat', 'lore', 'lotus', 'loveseat', 'lullaby',
  'luminary', 'lunaria', 'lynx', 'lyre', 'lyrebird', 'magnolia', 'magpie', 'mahogany', 'mallow',
  'mammal', 'mango', 'mantle', 'maple', 'marble', 'marigold', 'marimba', 'mariner', 'mask',
  'matinee', 'matron', 'mattress', 'meadow', 'memento', 'memoir', 'meniscus', 'menthol',
  'merchant', 'meringue', 'merlin', 'metal', 'meteor', 'midden', 'midnight', 'mildew', 'mill',
  'minaret', 'mindful', 'mink', 'minnow', 'mint', 'mire', 'mirror', 'miso', 'mist', 'mocha',
  'mochi', 'moment', 'monk', 'moon', 'moonbow', 'moor', 'moss', 'moth', 'mouse', 'muffin',
  'mushroom', 'muslin', 'nap', 'napkin', 'nebula', 'nectar', 'needle', 'nest', 'nettle',
  'newcomer', 'newt', 'niche', 'nimbus', 'nook', 'noon', 'nose', 'notch', 'novel', 'novella',
  'nugget', 'oak', 'oats', 'obelisk', 'ocean', 'ogre', 'oleander', 'olive', 'omega', 'onion',
  'operetta', 'orange', 'orangery', 'orbit', 'orchid', 'oriel', 'otter', 'outlier', 'overcoat',
  'overlook', 'owl', 'paddle', 'pagoda', 'palace', 'palette', 'palisade', 'palm', 'palomino',
  'panel', 'pangolin', 'panorama', 'pantry', 'parable', 'paramour', 'parlor', 'parlour', 'parquet',
  'parsley', 'passport', 'pastel', 'pasture', 'paw', 'peacoat', 'peafowl', 'pear', 'pearl', 'peat',
  'pebble', 'peerless', 'pelican', 'pelt', 'pendant', 'peony', 'pepper', 'pergola', 'peridot',
  'petal', 'pewter', 'phase', 'phosphor', 'pigeon', 'pilchard', 'pilgrim', 'pillar', 'pillow',
  'pine', 'pinecone', 'pinelike', 'placard', 'plain', 'plateau', 'plumage', 'plume', 'plumeria',
  'pocket', 'polestar', 'pollen', 'pomelo', 'poncho', 'pond', 'pondweed', 'pool', 'poppy', 'porch',
  'portage', 'portal', 'porthole', 'portico', 'postbox', 'potter', 'prairie', 'praxis', 'precept',
  'precinct', 'primrose', 'prism', 'promise', 'prowler', 'puddle', 'puffin', 'pulse', 'pumpkin',
  'purl', 'quagmire', 'quail', 'quarter', 'quartz', 'queendom', 'quibble', 'quill', 'quilt',
  'quilting', 'quince', 'quiver', 'rabbit', 'radish', 'raft', 'rail', 'railcar', 'rainbow',
  'ramble', 'ramshorn', 'raven', 'ravine', 'realm', 'recluse', 'redwood', 'reed', 'reef', 'refuge',
  'relic', 'remnant', 'requiem', 'reverie', 'ribbon', 'riddle', 'rig', 'rill', 'rim', 'ring',
  'ripple', 'river', 'riverbed', 'rook', 'rooster', 'rose', 'roseate', 'roseleaf', 'rosemary',
  'rowan', 'rowboat', 'rowlock', 'ruby', 'rudder', 'rumor', 'rune', 'saddle', 'saffron', 'sage',
  'sailboat', 'salt', 'salter', 'salvo', 'sampler', 'sanctum', 'sand', 'sandbar', 'sapling',
  'sapphire', 'sash', 'satchel', 'satin', 'savannah', 'scarf', 'schooner', 'scimitar', 'scroll',
  'sculptor', 'sea', 'seafarer', 'seafoam', 'seaglass', 'seasmoke', 'season', 'seastar', 'seawall',
  'secret', 'seed', 'seer', 'sentinel', 'sequel', 'sequoia', 'serpent', 'sextant', 'shade',
  'shadow', 'shale', 'sharkfin', 'shell', 'shepherd', 'shore', 'shower', 'shrine', 'sibyl',
  'sidepath', 'signpost', 'silk', 'silver', 'sinew', 'siren', 'skiff', 'skimmer', 'skyline',
  'slate', 'sleet', 'slipknot', 'slipper', 'slope', 'smoke', 'snail', 'snare', 'snow', 'snowbell',
  'soil', 'solace', 'solarium', 'solstice', 'songster', 'sonnet', 'sorrel', 'sorrow', 'soul',
  'sparkler', 'sparrow', 'spectra', 'speculum', 'sphinx', 'spillway', 'spindle', 'spire',
  'spoonful', 'spring', 'springer', 'sprout', 'spruce', 'spyglass', 'star', 'starfall', 'starlet',
  'statue', 'steeple', 'stone', 'storm', 'stratus', 'stream', 'sundial', 'sundog', 'sunrise',
  'surf', 'swallow', 'swamp', 'swan', 'sweetgum', 'sycamore', 'sylph', 'talisman', 'tallow',
  'talon', 'tapestry', 'tapir', 'tarn', 'teahouse', 'teak', 'tealight', 'tendril', 'terrace',
  'terrapin', 'terroir', 'thicket', 'thimble', 'thistle', 'thorn', 'thrush', 'tide', 'tideway',
  'timber', 'timbre', 'tinder', 'tinsmith', 'toad', 'tokenry', 'toolbox', 'topiary', 'torch',
  'totem', 'trackway', 'trail', 'transit', 'treasure', 'trellis', 'tricorn', 'trill', 'trimmer',
  'truffle', 'tryst', 'tulip', 'tumble', 'tundra', 'turret', 'turtle', 'tussock', 'twilight',
  'twine', 'unicorn', 'urchin', 'vagabond', 'valley', 'vane', 'vanity', 'vapor', 'veil', 'vellum',
  'velvet', 'verdant', 'vertex', 'vessel', 'vetiver', 'vicinity', 'vignette', 'villager', 'vine',
  'vineyard', 'violet', 'vitrine', 'volcano', 'voyager', 'wagtail', 'wain', 'walnut', 'wanderer',
  'warbler', 'warden', 'warren', 'watchman', 'wattle', 'waverly', 'wayside', 'weepers', 'weir',
  'wetstone', 'wharf', 'whelk', 'whelm', 'whim', 'whisker', 'whiskey', 'whistle', 'widow',
  'willow', 'wind', 'window', 'wisdom', 'wistaria', 'wisteria', 'wolf', 'woodland', 'wool',
  'workshop', 'wreath', 'writer', 'wyvern',
];
if (YOLO_NOUN.length !== 1024) throw new Error('YOLO_NOUN must be exactly 1024 entries');
window.YOLO_VERB = [
  'aches', 'adores', 'adorns', 'advances', 'agitates', 'ails', 'alights', 'alters', 'amazes',
  'anchors', 'answers', 'apes', 'appears', 'arches', 'arcs', 'arises', 'ascends', 'asks',
  'assures', 'attends', 'avoids', 'awaits', 'awakens', 'awes', 'balms', 'banishes', 'banks',
  'banters', 'bares', 'barters', 'basks', 'battles', 'bays', 'beams', 'beckons', 'becomes',
  'begets', 'beguiles', 'believes', 'belongs', 'bends', 'berates', 'bides', 'binds', 'bites',
  'blazes', 'blears', 'bleeds', 'blends', 'blesses', 'blinks', 'blooms', 'blossoms', 'blows',
  'broods', 'brushes', 'builds', 'burns', 'bustles', 'buzzes', 'calls', 'calms', 'canoes', 'cares',
  'carols', 'carves', 'casts', 'catches', 'catnaps', 'caves', 'ceases', 'chains', 'chants',
  'charms', 'chases', 'chats', 'cheers', 'chills', 'chimes', 'chirps', 'chokes', 'chooses',
  'circles', 'clamors', 'clangs', 'clasps', 'claws', 'cleans', 'clears', 'climbs', 'clings',
  'closes', 'clouds', 'clutches', 'coaxes', 'collects', 'combs', 'comes', 'comforts', 'commands',
  'conjures', 'consoles', 'contains', 'contends', 'cooks', 'cools', 'coos', 'cowers', 'crackles',
  'crafts', 'craves', 'crawls', 'creaks', 'creates', 'creeps', 'crests', 'cringes', 'crosses',
  'crouches', 'crowns', 'cruises', 'cubs', 'curls', 'curves', 'cycles', 'dabbles', 'dances',
  'darns', 'dashes', 'dawdles', 'dawns', 'dazzles', 'deafens', 'decays', 'deceives', 'declares',
  'deepens', 'defies', 'delays', 'delivers', 'demands', 'departs', 'descends', 'despairs',
  'detours', 'devours', 'dines', 'dips', 'dissents', 'dives', 'divides', 'divines', 'dotes',
  'doubts', 'dozes', 'drapes', 'draws', 'dreams', 'drifts', 'drinks', 'drips', 'droops', 'drops',
  'drowses', 'drums', 'dwells', 'earns', 'eases', 'ebbs', 'echoes', 'edges', 'elects', 'elevates',
  'embers', 'embodies', 'embraces', 'emerges', 'empties', 'enacts', 'encloses', 'ends', 'endures',
  'enfolds', 'engulfs', 'enjoys', 'enlivens', 'ensnares', 'enters', 'entwines', 'envies',
  'escapes', 'espies', 'evens', 'exhales', 'exists', 'exposes', 'fades', 'fails', 'falters',
  'fancies', 'fans', 'farrows', 'fasts', 'fathoms', 'favors', 'fears', 'fends', 'ferries',
  'fetches', 'fettles', 'fidgets', 'finds', 'fires', 'fishes', 'fits', 'flashes', 'flees',
  'flickers', 'flinches', 'flings', 'floats', 'floods', 'flows', 'flurries', 'flushes', 'flutters',
  'focuses', 'follows', 'foments', 'forages', 'forbids', 'forgets', 'forgives', 'forms', 'frames',
  'frees', 'frets', 'frolics', 'frosts', 'frowns', 'furls', 'gambles', 'gathers', 'gazes',
  'gentles', 'glances', 'gleams', 'glides', 'glimmers', 'glints', 'glistens', 'glitters', 'gloats',
  'glooms', 'glows', 'gnashes', 'goes', 'grabs', 'graces', 'grasps', 'grazes', 'greets', 'grieves',
  'grimaces', 'grinds', 'grins', 'grips', 'groans', 'grooms', 'grounds', 'grouses', 'growls',
  'guards', 'guesses', 'guests', 'guides', 'gushes', 'hallows', 'halts', 'handles', 'hangs',
  'happens', 'harkens', 'harrows', 'harvests', 'hastens', 'hatches', 'hates', 'hauls', 'haunts',
  'heals', 'hears', 'heartens', 'heats', 'heaves', 'hedges', 'heeds', 'heels', 'hems', 'herds',
  'hides', 'hinges', 'hints', 'hisses', 'hoards', 'holds', 'hollers', 'hollows', 'homes', 'honeys',
  'hopes', 'hovers', 'howls', 'huddles', 'hulls', 'hungers', 'hunts', 'hurries', 'hurts', 'hushes',
  'hustles', 'hymns', 'idles', 'ignites', 'illumes', 'imagines', 'implies', 'imports', 'indicts',
  'induces', 'indulges', 'infers', 'inflames', 'ingests', 'inhales', 'inherits', 'insists',
  'insures', 'intones', 'invades', 'invents', 'invites', 'joins', 'jokes', 'journeys', 'joys',
  'judges', 'juggles', 'jumps', 'keeps', 'kindles', 'kisses', 'kneads', 'kneels', 'knots', 'knows',
  'labors', 'lacks', 'ladles', 'lags', 'lambs', 'laments', 'lances', 'lapses', 'lashes', 'lasts',
  'latches', 'laughs', 'launches', 'laves', 'lavishes', 'leads', 'leans', 'leaps', 'learns',
  'leaves', 'lectures', 'leers', 'lends', 'lessens', 'letters', 'levels', 'licks', 'lightens',
  'lights', 'likens', 'lilts', 'lingers', 'listens', 'litters', 'lives', 'loathes', 'locks',
  'lodges', 'logs', 'loiters', 'lolls', 'looks', 'looms', 'loops', 'lopes', 'lords', 'loses',
  'lounges', 'loves', 'lowers', 'lubes', 'lulls', 'lumbers', 'lunges', 'lures', 'lurks', 'mends',
  'merges', 'mourns', 'muses', 'mutates', 'nears', 'nests', 'nods', 'nudges', 'obeys', 'offers',
  'opens', 'opts', 'orbits', 'outlasts', 'pains', 'paints', 'pants', 'parades', 'passes',
  'patrols', 'pauses', 'paves', 'paws', 'peeps', 'peers', 'perches', 'permits', 'persists',
  'petals', 'pierces', 'pines', 'pins', 'places', 'plants', 'plays', 'pleads', 'pledges', 'plucks',
  'plummets', 'plumps', 'poises', 'ponders', 'pools', 'pounces', 'pours', 'powers', 'praises',
  'prances', 'prays', 'preaches', 'presses', 'preys', 'prickles', 'primes', 'prospers', 'protests',
  'prowls', 'puffs', 'pulls', 'pulses', 'pumps', 'punts', 'purls', 'purrs', 'pushes', 'quickens',
  'quiets', 'quilts', 'races', 'radiates', 'rages', 'rains', 'rakes', 'rallies', 'rambles',
  'ranks', 'reaches', 'reads', 'reclaims', 'recoils', 'recounts', 'recovers', 'reforms', 'regrets',
  'rejoices', 'relents', 'relieves', 'relishes', 'renews', 'repents', 'replaces', 'reposes',
  'resides', 'resigns', 'resists', 'rests', 'returns', 'reveals', 'reveres',
];
if (YOLO_VERB.length !== 512) throw new Error('YOLO_VERB must be exactly 512 entries');
// Legacy export kept so any cached consumer doesn't break.
window.YOLO_WORDLIST = YOLO_NOUN;
